language: java
jdk: oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'

# Needed to execute some notebooks
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3  # give xvfb some time to start

install: ".travis/build.sh"
script: ".travis/test.sh"
